In [1]:
import pandas as pd
from sqlalchemy import create_engine, inspect

DB_URL = "postgresql+psycopg2://postgres:postgres@localhost:5432/olist"

engine = create_engine(DB_URL)

# Test the connection
with engine.connect() as connection:
    print("Connected to PostgreSQL successfully!")

Connected to PostgreSQL successfully!

In [2]:
inspector = inspect(engine)

tables = inspector.get_table_names()

print("Tables:")
for table in tables:
    print(table)

Tables:
olist_sellers
product_category_name_translation
olist_orders
olist_order_items
olist_customers
olist_geolocation
olist_order_payments
olist_order_reviews
olist_products

In [3]:
data = {}

for table in tables:
    data[table] = pd.read_sql_table(table, engine)
    
    print(f"{table}: {data[table].shape}")

olist_sellers: (3095, 4)
product_category_name_translation: (71, 2)
olist_orders: (99441, 8)
olist_order_items: (112650, 7)
olist_customers: (99441, 5)
olist_geolocation: (1000163, 5)
olist_order_payments: (103886, 5)
olist_order_reviews: (99224, 7)
olist_products: (32951, 9)

In [4]:
for table, df in data.items():
    print("=" * 60)
    print(f"TABLE: {table}")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")
    print("Columns:", df.columns.tolist())
    display(df.head(3))

============================================================
TABLE: olist_sellers
Rows: 3,095
Columns: 4
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ

============================================================
TABLE: product_category_name_translation
Rows: 71
Columns: 2
Columns: ['product_category_name', 'product_category_name_english']

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto

============================================================
TABLE: olist_orders
Rows: 99,441
Columns: 8
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

============================================================
TABLE: olist_order_items
Rows: 112,650
Columns: 7
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

============================================================
TABLE: olist_customers
Rows: 99,441
Columns: 5
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP

============================================================
TABLE: olist_geolocation
Rows: 1,000,163
Columns: 5
Columns: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP

============================================================
TABLE: olist_order_payments
Rows: 103,886
Columns: 5
Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71

============================================================
TABLE: olist_order_reviews
Rows: 99,224
Columns: 7
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,None,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,None,2018-02-17 00:00:00,2018-02-18 14:36:24

============================================================
TABLE: olist_products
Rows: 32,951
Columns: 9
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

# Check keys and duplicates

In [5]:
orders = data["olist_orders"]

print("Orders:", len(orders))
print("Unique order_id:", orders["order_id"].nunique())
print("Duplicate order_id:", orders["order_id"].duplicated().sum())

Orders: 99441
Unique order_id: 99441
Duplicate order_id: 0

In [6]:
customers = data["olist_customers"]

print("Customers:", len(customers))
print("Unique customer_id:", customers["customer_id"].nunique())
print("Duplicate customer_id:", customers["customer_id"].duplicated().sum())

Customers: 99441
Unique customer_id: 99441
Duplicate customer_id: 0

In [7]:
order_items = data["olist_order_items"]

print("Order items:", len(order_items))
print("Unique order_id:", order_items["order_id"].nunique())
print("Rows per order:")
display(order_items.groupby("order_id").size().value_counts().sort_index().head())

Order items: 112650
Unique order_id: 98666
Rows per order:

1    88863
2     7516
3     1322
4      505
5      204
Name: count, dtype: int64

In [8]:
payments = data["olist_order_payments"]

print("Payments:", len(payments))
print("Unique order_id:", payments["order_id"].nunique())
print("Rows per order:")
display(payments.groupby("order_id").size().value_counts().sort_index().head())

Payments: 103886
Unique order_id: 99440
Rows per order:

1    96479
2     2382
3      301
4      108
5       52
Name: count, dtype: int64

In [9]:
products = data["olist_products"]

print("Products:", len(products))
print("Unique product_id:", products["product_id"].nunique())
print("Duplicate product_id:", products["product_id"].duplicated().sum())

Products: 32951
Unique product_id: 32951
Duplicate product_id: 0

In [10]:
sellers = data["olist_sellers"]

print("Sellers:", len(sellers))
print("Unique seller_id:", sellers["seller_id"].nunique())
print("Duplicate seller_id:", sellers["seller_id"].duplicated().sum())

Sellers: 3095
Unique seller_id: 3095
Duplicate seller_id: 0

In [11]:
for table in ["olist_order_reviews", "olist_geolocation", "product_category_name_translation"]:
    df = data[table]
    
    print("=" * 60)
    print(table)
    print("Rows:", len(df))
    print("Columns:", df.columns.tolist())
    print(df.head(2))

============================================================
olist_order_reviews
Rows: 99224
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33

   review_score review_comment_title review_comment_message  \
0             4                 None                   None
1             5                 None                   None

  review_creation_date review_answer_timestamp
0  2018-01-18 00:00:00     2018-01-18 21:46:59
1  2018-03-10 00:00:00     2018-03-11 03:05:13
============================================================
olist_geolocation
Rows: 1000163
Columns: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
============================================================
product_category_name_translation
Rows: 71
Columns: ['product_category_name', 'product_category_name_english']
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories

# build the ML table

In [12]:
ml_table = orders.copy()

print("Starting rows:", len(ml_table))
print("Unique orders:", ml_table["order_id"].nunique())

Starting rows: 99441
Unique orders: 99441

# Aggregate BEFORE joining

In [13]:
items_agg = (
    order_items
    .groupby("order_id")
    .agg(
        item_count=("order_item_id", "count"),
        product_count=("product_id", "nunique"),
        seller_count=("seller_id", "nunique"),
        total_price=("price", "sum"),
        total_freight=("freight_value", "sum")
    )
    .reset_index()
)

display(items_agg.head())

,order_id,item_count,product_count,seller_count,total_price,total_freight
0,00010242fe8c5a6d1ba2dd792cb16214,1,1,1,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,1,1,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,1,1,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,1,1,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,1,1,199.90,18.14

In [14]:
payments_agg = (
    payments
    .groupby("order_id")
    .agg(
        payment_count=("payment_sequential", "count"),
        payment_value=("payment_value", "sum"),
        max_installments=("payment_installments", "max")
    )
    .reset_index()
)

display(payments_agg.head())

,order_id,payment_count,payment_value,max_installments
0,00010242fe8c5a6d1ba2dd792cb16214,1,72.19,2
1,00018f77f2f0320c557190d7a144bdd3,1,259.83,3
2,000229ec398224ef6ca0657da4fc703e,1,216.87,5
3,00024acbcdf0a6daa1e931b038114c75,1,25.78,2
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,218.04,3

# Join

In [15]:
customer_info = customers[
    [
        "customer_id",
        "customer_unique_id",
        "customer_city",
        "customer_state"
    ]
]

ml_table = ml_table.merge(
    customer_info,
    on="customer_id",
    how="left",
    validate="many_to_one"
)

print(ml_table.shape)

(99441, 11)

In [16]:
ml_table = ml_table.merge(
    items_agg,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print(ml_table.shape)

(99441, 16)

In [17]:
ml_table = ml_table.merge(
    payments_agg,
    on="order_id",
    how="left",
    validate="one_to_one"
)

print(ml_table.shape)

(99441, 19)

# Validate

In [18]:
print("Rows:", len(ml_table))
print("Unique orders:", ml_table["order_id"].nunique())
print("Duplicate orders:", ml_table["order_id"].duplicated().sum())

Rows: 99441
Unique orders: 99441
Duplicate orders: 0

In [19]:
assert ml_table["order_id"].is_unique

print("ML table contains exactly one row per order")

ML table contains exactly one row per order

In [20]:
print("Final shape:", ml_table.shape)

display(ml_table.head())

print("\nMissing values:")
display(ml_table.isna().sum().sort_values(ascending=False).head(10))

Final shape: (99441, 19)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_city,customer_state,item_count,product_count,seller_count,total_price,total_freight,payment_count,payment_value,max_installments
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,1.0,1.0,1.0,29.99,8.72,3.0,38.71,1.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,barreiras,BA,1.0,1.0,1.0,118.70,22.76,1.0,141.46,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,1.0,1.0,1.0,159.90,19.22,1.0,179.12,3.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,1.0,1.0,1.0,45.00,27.20,1.0,72.20,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,1.0,1.0,1.0,19.90,8.72,1.0,28.62,1.0

Missing values:

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
item_count                        775
total_freight                     775
total_price                       775
seller_count                      775
product_count                     775
order_approved_at                 160
max_installments                    1
payment_value                       1
dtype: int64

# Save the artifact

In [22]:
ml_table.to_parquet(
    "../artifacts/ml_table.parquet",
    index=False
)

print("ml_table.parquet saved")

ml_table.parquet saved

In [24]:
saved = pd.read_parquet("../artifacts/ml_table.parquet")

assert saved["order_id"].is_unique

print("Artifact verified")
print("Shape:", saved.shape)
print("Rows:", len(saved))
print("Unique orders:", saved["order_id"].nunique())
print("Duplicate orders:", saved["order_id"].duplicated().sum())

Artifact verified
Shape: (99441, 19)
Rows: 99441
Unique orders: 99441
Duplicate orders: 0

## Notebook 1 Summary

The database tables were inspected individually to understand their row meaning,
keys, and relationships.

The `olist_orders` table was used as the base table because each row represents one order.

The `olist_order_items` and `olist_order_payments` tables contain multiple rows per order,
so they were aggregated to the order level before joining.

Customer information was joined using `customer_id`.

The final ML table contains exactly one row per order and was saved as:

`../artifacts/ml_table.parquet`